open! Core

(** Dijkstra over full-body configurations (§4.12). Nodes are player states
    deduplicated by a BUCKETED key (torso position and stamina are bucketed —
    §4.12 — so near-identical states collapse and the space stays tractable;
    the bucketing can prune, never invent: every edge is generated by the
    real gate, so any returned route replays through the game verbatim).

    Why Dijkstra over BFS: BFS minimizes moves; Dijkstra minimizes weighted
    effort (stamina + chalk + risk), which is what "the intended route"
    means in this game. *)

type action =
  | Move of Types.limb * int (* hold id *)
  | Rest
  | Chalk of Types.limb
[@@deriving sexp_of, compare, equal]

(* §4.14 difficulty metrics. [misleading_branches] and [route_families]
   arrive with the generator (Phase 6). [min_stamina_remaining] is the
   lowest the tank gets at ANY point on the optimal route.
   [chalk_required] counts the chalk ACTIONS on the route (refill holds can
   mask net bag drawdown). *)
type metrics =
  { optimal_cost : int
  ; optimal_moves : int
  ; chalk_required : int
  ; min_stamina_remaining : int
  ; states_expanded : int
  ; max_queue_size : int
  ; critical_balance_turns : int
  }
[@@deriving sexp_of]

type solution =
  { actions : action list
  ; metrics : metrics
  }
[@@deriving sexp_of]

type outcome =
  | Solution of solution
  | No_route of { states_expanded : int } (* search space exhausted: unwinnable *)
  | Search_limit of { states_expanded : int } (* Config.solver_max_states hit *)
[@@deriving sexp_of]

(** [blocked] adds extra unusable holds on top of the crumbling-holds rule —
    pass [Set.empty (module Int)] normally; route-family counting (§4.14)
    blocks the optimal route's key holds and re-solves. *)
val solve
  :  blocked:Set.M(Int).t
  -> wall:Types.wall
  -> start:Types.player_state
  -> outcome
